### ISSUE TITLE
can't compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by slr** [notsecure/uTox#157]
at first I installed some required libs:

```
sudo apt-get install libalut-dev libxft-dev libv4l-dev libdbus-1-dev
```

after I added essential keys:

```
-I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include
```

so the command is:

```
cc -o uTox.o *.c ./png/png.c -lX11 -lXft -lXrender -ltoxcore -ltoxav -ltoxdns -lopenal -pthread -lresolv -ldl -lm -lfontconfig -lv4lconvert -lvpx -I/usr/include/freetype2 -ldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include
```

but result is bad:

```
/tmp/ccq4GzwF.o: In function `notify_build_message':
main.c:(.text+0xa4f): undefined reference to `dbus_message_iter_init_append'
main.c:(.text+0xa6f): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xa95): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xabb): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xade): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xb01): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xb32): undefined reference to `dbus_message_iter_open_container'
main.c:(.text+0xb53): undefined reference to `dbus_message_iter_close_container'
main.c:(.text+0xb84): undefined reference to `dbus_message_iter_open_container'
main.c:(.text+0xbb8): undefined reference to `dbus_message_iter_open_container'
main.c:(.text+0xbe1): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xc17): undefined reference to `dbus_message_iter_open_container'
main.c:(.text+0xc42): undefined reference to `dbus_message_iter_append_basic'
main.c:(.text+0xc68): undefined reference to `dbus_message_iter_close_container'
main.c:(.text+0xc8c): undefined reference to `dbus_message_iter_close_container'
main.c:(.text+0xcad): undefined reference to `dbus_message_iter_close_container'
main.c:(.text+0xcd3): undefined reference to `dbus_message_iter_append_basic'
/tmp/ccq4GzwF.o: In function `dbus_notify':
main.c:(.text+0xd01): undefined reference to `dbus_error_init'
main.c:(.text+0xd14): undefined reference to `dbus_bus_get'
main.c:(.text+0xd22): undefined reference to `dbus_error_is_set'
main.c:(.text+0xd4d): undefined reference to `dbus_error_free'
main.c:(.text+0xd7c): undefined reference to `dbus_message_new_method_call'
main.c:(.text+0xd9d): undefined reference to `dbus_message_set_auto_start'
main.c:(.text+0xdb0): undefined reference to `dbus_message_set_destination'
main.c:(.text+0xddd): undefined reference to `dbus_error_init'
main.c:(.text+0xdfe): undefined reference to `dbus_connection_send_with_reply'
main.c:(.text+0xe56): undefined reference to `dbus_pending_call_set_notify'
main.c:(.text+0xe71): undefined reference to `dbus_connection_read_write_dispatch'
main.c:(.text+0xe85): undefined reference to `dbus_message_unref'
main.c:(.text+0xe90): undefined reference to `dbus_connection_unref'
/tmp/ccq4GzwF.o: In function `listpopup':
main.c:(.text+0x2d50): undefined reference to `gtk_listpopup'
/tmp/ccq4GzwF.o: In function `png_to_image':
main.c:(.text+0x332e): undefined reference to `lodepng_decode32'
/tmp/ccq4GzwF.o: In function `doevent':
main.c:(.text+0x435e): undefined reference to `lodepng_encode_memory'
/tmp/ccq4GzwF.o: In function `video_init':
main.c:(.text+0x5f61): undefined reference to `XShmCreateImage'
main.c:(.text+0x6017): undefined reference to `XShmAttach'
/tmp/ccq4GzwF.o: In function `video_close':
main.c:(.text+0x605f): undefined reference to `XShmDetach'
/tmp/ccq4GzwF.o: In function `video_getframe':
main.c:(.text+0x6155): undefined reference to `XShmGetImage'
collect2: error: ld returned 1 exit status
```

similar problem with command

```
cc -o uTox.o *.c ./png/png.c -lX11 -lXft -lXrender -ltoxcore -ltoxav -ltoxdns -lopenal -lsodium -lopus -lvpx -lm -pthread -lresolv -ldl -lfontconfig -lv4lconvert -I/usr/include/freetype2 -ldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-1.0/include
```

result is:

```
/tmp/cc7G3cIR.o: In function `listpopup':
main.c:(.text+0x2d50): undefined reference to `gtk_listpopup'
/tmp/cc7G3cIR.o: In function `video_init':
main.c:(.text+0x5f61): undefined reference to `XShmCreateImage'
main.c:(.text+0x6017): undefined reference to `XShmAttach'
/tmp/cc7G3cIR.o: In function `video_close':
main.c:(.text+0x605f): undefined reference to `XShmDetach'
/tmp/cc7G3cIR.o: In function `video_getframe':
main.c:(.text+0x6155): undefined reference to `XShmGetImage'
collect2: error: ld returned 1 exit status
```

I can't understand the code for now, therefore I report this and ask help.
